module.exports = [ // Ethically sourced from your local 2b2t!
    '2n2s is full',
    'how interesting',
    'DIAMONDS!',
    'kill or be killed',
    'Proxy connections disabled due to an exploit',
    'welcome to die',
    'Everyone is a shit',
    'Real life sucks anyway!',
    'eat shit and die', // Funny
    'Now with circles',
    'hopefully you posted this ironically',
    'SIX YEARS',
    'Time to smoke weed and eat pizza',
    'An exploit was disabled due to',
    "!!! CRINGE WARNING !!!",
    "'Autism' has more than 300 definitions here",
    "'like' us on facebook!",
    "'vanilla'",
    "+78940 x +154340 z",
    "-NO TRANNIES ALLOWED - FP MALES ONLY",
    "/ignore is your only friend here.",
    "/kill",
    "1 BEST DATING SERVER",
    "1 was the original number",
    "1.13 when",
    "1.14 Expected sometime soon",
    "1.15 Expected sometime soon",
    "100% lag free",
    "100% organic",
    "144p GAMEPLAY!",
    "2B2T.ORG IS THE BEST MINECRAFT SERVER",
    "127.1 IS THE BEST MINECRAFT SERVER",
    "2T",
    "2b2t and smoke weed",
    "2b2t is Narnia",
    "2b2t is full",
    "2b2t is full ya know",
    "2b2t peaceful smp happy people on!",
    "2b2t woop woop",
    "2b2t> home of the largest CP pixel art collection",
    "2bombs2terrorists",
    "2builders2terrorists",
    "2twin2towers",
    "62031/66/-202890",
    "666 Kill Hitler 666",
    "666! The number of the beast!",
    "<insert meme here>",
    "> has voted",
    ">Did you know? No, you didn't!",
    ">HEY LOOK GUYS I FIGURED OUT",
    ">Rules",
    ">serious pvpers",
    ">wooga",
    "A blackhole of destruction into",
    "A little fruity",
    "A oeaceful christian server",
    "AAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AS SEEN ON TV",
    "Accept it.",
    "Alea iacta est.",
    "All aboard the Vetrain!",
    "All aboard the vetrain",
    "All praise the Melon Goddess!",
    "All servers are located in a hut in cuba",
    "All that you know will fade...",
    "All your friends are online!",
    "An exploit was disabled due to",
    "An uncontained SCP.",
    "And",
    "Any cute girls on today :3",
    "Anyone wanna grief the Valley of Wheat?",
    "As seen on /b/!",
    "As seen on /co/",
    "Ask about the cactus dupe!",
    "Autistic screeching ahead",
    "BEHOLD.",
    "BIGGEST BATTLE IN 2B2T HISTORY!!",
    "BIGGEST GRIEF IN 2B2T HISTORY!!",
    "BIGGEST VILLAGE IN MINECRAFT!!",
    "BIRD UP!",
    "Best christian factions server.",
    "Birds are disabled due to an exploit",
    "Bite my shiny metal ass",
    "Block game drama",
    "Blocks are disabled due to an exploit",
    "Break a block, then break it again!",
    "Burn it, burn it all!",
    "Burst some Pepsi out!",
    "But there's already one that is just like this?",
    "COMMUNICATION ERROR",
    "Cactus dupe is best dupe.",
    "Can't Connect To Server (in red)",
    "Can't connect to server.",
    "Certified Mojang Testing Grounds.",
    "Chill, it's just a block game.",
    "Clown down!",
    "Cogito, ergo sum.",
    "Coming Soon, 2b2tCon!",
    "Crafting is disabled due to an exploit",
    "Crystal PvP is the only PvP",
    "DEDICATION MOTIVATION ACCELERATION",
    "DEEP FREEZE DEEP FREEZE DEEP FREEZE",
    "DELETE THIS",
    "Daily reminder that AgentGB won the war",
    "Daily reminder to brush your teeth.",
    "Dead server, don't join",
    "Death ahead",
    "Death is only a temporary inconvenience.",
    "Delet This!",
    "Deplorables Anonymous",
    "Destroy Build Destroy: Minecraft edition",
    "Did You Bring the Cheese",
    "Did you know?",
    "Did you know? No you didn't!",
    "Did you know? No, you didn't!",
    "Disiecta membra poetae.",
    "Do you have a moment to talk about our",
    "Do you is fucking?",
    "Does anybody have food?",
    "Don't dig straight down!",
    "Don't eat yellow snow!",
    "Don't look behind you.",
    "Dont even start, turn around",
    "Drink Pepsi everyday!",
    "Dupe your cactus with the cactus dupe!",
    "Egg!",
    "Either. Or Both. Depends on perspective.",
    "Elitist regulars inside!",
    "Enjoy!",
    "Ever had a fresh bite of WINTERMELON?",
    "Every Time Lightning strikes, a veterean dies",
    "Every day is the same!",
    "Everyone is a shit",
    "Everyone on 2b2t is a bot except you",
    "Exploits are temporarily disabled",
    "FACTIONS|PRISON|ARENAPVP",
    "FIVE YEARS",
    "FIX THE LADDERS",
    "FOUR YEARS",
    "Family Friendly Christian server!",
    "Fishing is temporarily disabled",
    "Fit did nothing wrong",
    "Fit good, but rush",
    "Fix the damn end portals",
    "Format your hard drive today!",
    "Free Door Giveaway!",
    "Free diamonds for youtubers",
    "GET UP ON THE HYDRA'S BACK",
    "GIT GUD",
    "GOD WILL NOT SAVE YOU HERE",
    "Game time started",
    "Get on the bus, leave it all to us",
    "Get out of my chair!",
    "Go away, we're full.",
    "Good luck.",
    "HACKEDBYTEAMRUSHER!",
    "HATEHATEHATEHATEHATEHATEHATEHATE",
    "HE WILL NOT DIVIDE US",
    "HEY GUYS AND WELCOME BACK TO ANOTHER...",
    "HEY LOOK GUYS I FIGURED OUT",
    "Happiness only real when shared",
    "Happy birthday to my wife",
    "Happy senior man approves this message!",
    "Heavily Moderated",
    "Hell is empty and all the devils are here.",
    "Here's your daily dose of autism.",
    "Hey kid, wanna join #TeamVetrain?",
    "Home is where the deception happens",
    "Home of the Vetain and rasher war",
    "Hookers and Blow!",
    "Horse+Forest=RageQuit",
    "Hotdogs, hamburgers, hookers and blow",
    "How do i green text?",
    "How its cqlled when you reach a black hole?",
    "I Got Big Booty Bitches, Big, Big, Booty Bitches",
    "I am the church",
    "I could kill you all in 3 seconds.",
    "I fucking love eggplants",
    "I hate God because my crush didn't like me",
    "I hope not but oh well",
    "I just mined 1 TNT!",
    "I just mined 14 Dirt!",
    "I just mined one bedrock!",
    "I just picked up 64 Netherrack!",
    "I knew you would be back!",
    "I laugh to hide the pain",
    "I look around, I look around,",
    "I only wanted what was best for her...",
    "I recognize that block,",
    "I solemnly swear I don't have a life...",
    "I spent three hours last night trying to get Tweek's parents to stop griefing my castle!",
    "I want to die. It's not a joke anymore.",
    "I will now be looking at the MOTD's",
    "I'm just wandering around my base aimlessly,",
    "I'm new can I have food",
    "I'm not gay, but $20 is $20",
    "ITS ALL CONNECTED",
    "If you are thinking about joining call this number",
    "Investigate 3/11",
    "It does not end.",
    "It is crying.",
    "It is inevitable.",
    "It is meaningless.",
    "It was always a temporary map",
    "It will all be over soon.",
    "It will be done my Lord",
    "It's all connected!",
    "It's called destroy, not grief",
    "It's downward from here",
    "It's more of a hell than the nether",
    "It's sandcastles man",
    "It's wabbit season!",
    "Its dangerous to go alone, take this melon",
    "Jesus approves vetarians",
    "Jet fuel can't melt iron blocks",
    "Join team vetrain today!",
    "Joining is now disabled due to an exploit.",
    "Journey before Destination",
    "Journey to the world border!",
    "Just 5 More Minutes...",
    "Just ask for trees!",
    "Just don't read chat",
    "Just pretend it's yogurt",
    "Just when I thought I was out,",
    "Kek!",
    "Kek'd and check'd.",
    "Kill them all... before they kill you...",
    "LEGALIZE RANCH!",
    "LET ME IIIIIINN",
    "Leave now while you still can.",
    "Let go.",
    "Lets Play A Game...",
    "Like No Other",
    "Live Free, Die Hard!",
    "Logging in is temporarily disabled",
    "Look around... They will all betray you...",
    "Look at me.",
    "MAKE AMERICA GREAT AGAIN!",
    "MOTD has been disabled due to an exploit",
    "Made in North Korea",
    "Maintain a positive attitude!",
    "Make Fort Dick Great Again!",
    "More than a meme",
    "My heart is at The Lands.",
    "My horse fucking disintegrated",
    "My horse just vanashed",
    "My stepdads play here",
    "NEW DUPE, GET ON!",
    "NEW WEBSITE UP VERY SOON!",
    "NO GO AWAY DON'T COME HERE YOU CAN'T L",
    "NOW DO THE HARLEM SHAKE",
    "Name a wither at spawn",
    "Nationwide is on your side",
    "New dupe discovered!",
    "New map!!!!",
    "No Step On Snek",
    "No anime Mapart allowed",
    "No! Not Gravy! Nooooooo!",
    "No, I won't get out of your shed.",
    "No.",
    "Nobody is amused",
    "Not actually the oldest server in Minecraft.",
    "Not your personal daycare.",
    "Notch approved server!",
    "Nothing ever lasts",
    "Now 100% Faction Free!",
    "Now hiring! Jews in sombreros",
    "Now with 100% more end!",
    "Now with circles",
    "Now with daily doses of crashes!",
    "Now with kits!",
    "Null",
    "OBEY",
    "ONE YEAR",
    "OOMPALOOMPA.avi",
    "Official Mojang Testing Grounds",
    "Oh shit it's going down",
    "Oh shoot",
    "Once you join YOU CAN'T UNJOIN",
    "Or try our diet edition",
    "Our horses have dicks!",
    "OwO What's this?",
    "PEPIS BENIS",
    "PRAISE OUR LORD AND SAVIOR, DONKEH",
    "PVP has been disabled due to an exploit",
    "Pain and misery follow",
    "Pinging...",
    "Placing blocks is now disabled due to an exploit",
    "Please stop destroying my spawn",
    "Pocket edition is better",
    "Position in queue: 1835",
    "Position in queue: 940",
    "Praise be thy melon!",
    "Pretend its 2013 everyday!",
    "Problems are not stop signs, they are guidelines.",
    "Proud Sponsor of My Little Pony",
    "RC Cola > Pepsi",
    "REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "ROBLOX IS BETTER",
    "Rated R for retardation",
    "Real life sucks anyway!",
    "Real life sucks anyways.",
    "Red Pill or Blue Pill",
    "Remember to be friendly!",
    "Remember to tame parrots with cookies!",
    "Right or wrong, it's very pleasant",
    "Roleplay dupe is best dupe.",
    "Rules",
    "S U C C",
    "SEVEN YEARS",
    "SHUT IT DOWN",
    "SIX YEARS",
    "SMIB SMIB SMIB SMIB",
    "SUBMIT! SUBMIT! SUBMIT! SUBMIT! SUBMIT! SUBMIT!",
    "SUPERJAIL",
    "See you @30mil",
    "See! I do care!",
    "Self improvement is masturbation.",
    "Semper inops quicumque cupit.",
    "Server for SoundCloud rappers only",
    "Server shutting down in 5 seconds.",
    "Shoo-Bee-Doo, Shoo-Shoo Bee-Doo",
    "Show off your digital girth!",
    "Shulkerbox in a shulkerbox in a shulkerbox in a...",
    "Si vis pacem, para bellum.",
    "Singleplayer with cancerous chat.",
    "Sleep deprivation is a drug.",
    "So hard to die.",
    "Something new disabled weekly!",
    "Sooner or later,",
    "Sound disabled due to an exploit",
    "Spawn is disabled due to an exploit",
    "Sponsored by the Trump Administration.",
    "Surprisingly chewey.",
    "Swearing is a big no no it will result in a ban",
    "TEAMMENTOS",
    "THAT'S THE POWER OF THE KEYBLADE!",
    "THAW THAW THAW THAW THAW THAW THAW THAW",
    "THE DUPE IS DEAD!!!",
    "THE FINAL FRONTIER",
    "THERE IS NO SAFE",
    "THREE YEARS",
    "TO GET OUT OF SPAWN YOU NEED TO EAT",
    "TRUST NO ONE.",
    "TRUTH ABOUT FIT'S BASE EXPOSED!!",
    "TWO YEARS",
    "TYRONE IS POBBOB!1!1!!1!1!1!!1!1!!!1",
    "Team veterinarian",
    "Temp map.",
    "The Beginning of The End is HERE!!!",
    "The Minecraft equivalent of a Diseny attraction",
    "The Oldest Christian Family Friendly Server!!",
    "The Zone will consume you.",
    "The best 2b2t clone",
    "The darkness spreads.",
    "The disabling of exploits has been disabled",
    "The nether is now disabled",
    "The reason trump won",
    "The shit storm is obvious now",
    "The world oldest Faction server",
    "There are currently 3 working dupes",
    "There is always a dupe",
    "There is always a workaround.",
    "There is no escape...",
    "There is still salvation and hope for you",
    "There's always a dupe!",
    "There's no right, there's no wrong,",
    "They told me I could write anything",
    "They will betray you.",
    "This MOTD requires a 2b2t GOLD account™.",
    "This again...",
    "This ends you.",
    "This is a sever MOTD message",
    "This is alien to me.",
    "This place is scary.",
    "This server is clickbait",
    "This server is immortal",
    "Time to smoke weed and eat pizza",
    "Time will become your worst enemy,",
    "Traps are not gay!",
    "Trust everyone",
    "Trust is your weakness...",
    "Trust me, I'm a doctor.",
    "Trust no one",
    "Twilight Sparkle is best pony.",
    "Type /kill cow for steak!",
    "Type /kill yes or /kill no to vote!",
    "UNDEAD",
    "Use the 1.12 narrator.",
    "WALL",
    "WELCOME TO DIE",
    "WHO IS MINING VINES AND OBSIDIAN???",
    "Walking is temporarily disabled due to an exploit",
    "Want to build a base together?",
    "We all never belonged here,",
    "We are an equal opportunity community",
    "We found your stash",
    "We live in a society.",
    "We live in the Society",
    "We need a new dupe.",
    "We're so far out!",
    "Welcome Back",
    "Welcome to the oldest server in Minecraft!",
    "Welcome, Dave",
    "Well, at least we still have maps.",
    "What can change the nature of man?",
    "What is a MOTD?",
    "What?",
    "Whats the reason for joining this time?",
    "Where Tradition Meets Tomorrow",
    "Where am I going?",
    "Where is the mellon highway",
    "Where'd you go, psycho boy?",
    "Where's the lamb sauce!?",
    "Which SCP number is 2b2t?",
    "Why are we still here? Just to suffer?",
    "Worlds Best Cup of Coffee!",
    "X 145,200 Y 63 Z -803,450",
    "YES NO YES NO YES NO YES NO YES NO YES NO",
    "Yeah I have made a mistake",
    "Yes please",
    "You are the reason this place is on a watchlist.",
    "You can never leave this place.",
    "You can never leave. It never ends.",
    "You can't change spawn.",
    "You could have stopped it.",
    "You didn't think that was it did you?",
    "You die when you are killed.",
    "You have nowhere else to go!",
    "You hear my name, you will know who I am.",
    "You thought it was over,",
    "You will be alone in the end...",
    "You won't last long here",
    "You're already dead",
    "You're here forever.",
    "Your inbox has (13) new messages",
    "[deleted]",
    "a mountain of rubble and death",
    "actualy, yes i did have a bite",
    "already a map of north korea",
    "also i'd just like to thank you for",
    "also, i like to make the sex with the doritos",
    "an everlasting war between order and chaos",
    "as seen on TV!",
    "backdoor'd",
    "blaze it faggot",
    "block game hell since 2010",
    "buy more coke right now",
    "call of duty rejects in this server",
    "christian mlp anarchy server",
    "co-ordinates are currency",
    "coke > pepsi",
    "consider yourself sacrificed",
    "cringey",
    "dark souls of minecraft",
    "dead forever",
    "dead geam",
    "delete this",
    "do /kill veteran to join #team veteran",
    "dont ask questions",
    "dont join this is virused",
    "eat a shit FAGOT",
    "edgelord teenagers in this server",
    "edgy sentence here",
    "end of the line",
    "even the border is griefed",
    "feel free to build 10k out",
    "fitsgoodbutrush",
    "friendly players on",
    "fucc",
    "fun fact this server is played by mimes",
    "gamer time",
    "git gud",
    "give the suc",
    "goates",
    "has voted",
    "have you ever seen a",
    "he said max of three you fucling sperg",
    "hggh ygh yg",
    "history.3gp",
    "hopefully you posted this ironically",
    "how do i dupe donkies",
    "how do i get food",
    "how to escape spawn!!! help pls!!!",
    "i am not gay i promise",
    "i dont come here for the game",
    "i log on about 6 times a day",
    "im using ubuntu but i might buy a linux computer",
    "internet game shithole",
    "is this sever stone made ?",
    "its all connected guays",
    "its backdoored dont join",
    "its only a block game",
    "join /r/2b2t!",
    "join our digital lego club today!",
    "join r/2b2t!",
    "lag is good",
    "least advertised server ever",
    "lets play 2b2t!",
    "look, he's dead",
    "looking for moderators apply now!",
    "max of 3?",
    "may contain nuts.",
    "mellons",
    "memes were disabled due to an exploit",
    "mom its just a entire day wasted",
    "more than just a block game",
    "mountains get big because",
    "my syndrome may be down,",
    "needs more fire",
    "never forget donkeycaust",
    "nice",
    "nothing ever lasts, so just give up now",
    "now activating THE WUKON MACHINE",
    "now with midroll ads!",
    "of all the things youv'e lost,",
    "ok",
    "once you go black you never go back",
    "one who sees all",
    "op is a faggot",
    "ores before whores",
    "peace of shit lag",
    "peice of a shit lag",
    "pepsi > all other",
    "pepsi > coke",
    "plos help i am vetrin member",
    "praise Shrek",
    "praise praise praise praise praise",
    "pushin rope, all day, every day",
    "rebirth",
    "remember, no rashen",
    "removed cactus dupe",
    "rrerr",
    "sample text",
    "serious pvpers",
    "shitty graphics",
    "silentpedro.mp4",
    "smh tbh fam",
    "soon a map of north korea",
    "spank me daddy RAWN xD",
    "sponsored by church taxes",
    "stop reading this and start",
    "succ",
    "the best minecraft server in the universe",
    "the diamond",
    "the yacht heist in under 6 minutes",
    "this is a christian server, do not swear",
    "this is not a fractions server",
    "this is now dead",
    "this is why we can't have nice things",
    "trigonometry has no real world applications",
    "two bee two tee dot org",
    "u w0t m9?",
    "unstoppable",
    "ur mom plays here",
    "want to build a base together?",
    "we will fuck ur mom",
    "website:",
    "welcome to spawn",
    "wew lad",
    "what are you waiting for?",
    "what command to tp",
    "what is a 'grief' anyway?",
    "what is real anymore",
    "whats a 2b2?????",
    "where are the maps?",
    "where does the ocean end ??",
    "which side are you, joe",
    "who is this mysterious and",
    "who turned out the lights",
    "who's mining obsidian and vines",
    "whomst'd've broke my maps!",
    "why am I suffocating",
    "why do i feel pain",
    "why is avacado so expensive?",
    "wooga",
    "yiff",
    "you are banned from this server,",
    "you find all types of people,",
    "you never know, it may just make it to the MOTD",
    "you still play minecraft?",
    "you'll be back, you'll always be back",
    "your boat looks terrible,",
    '\u00A74Can\'t connect to server'
]